/**
 * PHASE 1 DEMO DATA
 * -------------------------------------------------------------------------
 * Everything in this file is mock/demo data used only for visual
 * presentation during Phase 1. None of it is read from or written to
 * Supabase. In Phase 2, every import of this file will be replaced with
 * real Supabase queries (see lib/supabase/*). Keeping this isolated here
 * makes that swap mechanical instead of requiring a UI rewrite.
 */
import { Project, Expense, ExpenseCategory, AppDocument } from "@/types";

export const demoCategories: ExpenseCategory[] = [
  { id: "1", name: "Materials", description: null, is_active: true, created_at: "" },
  { id: "2", name: "Labor", description: null, is_active: true, created_at: "" },
  { id: "3", name: "Equipment", description: null, is_active: true, created_at: "" },
  { id: "4", name: "Transportation", description: null, is_active: true, created_at: "" },
  { id: "5", name: "Fuel", description: null, is_active: true, created_at: "" },
  { id: "6", name: "Tools", description: null, is_active: true, created_at: "" },
  { id: "7", name: "Other", description: null, is_active: true, created_at: "" },
];

export const demoProjects: Project[] = [
  {
    id: "p1",
    project_code: "PRJ-2026-001",
    name: "Sprinkler System Installation",
    client_name: "Ayala Land Corp.",
    site_location: "Makati City",
    service_type: "Fire Sprinkler System",
    description: "Full sprinkler installation for a 12-storey commercial building.",
    contract_value: 3200000,
    budget: 2500000,
    status: "active",
    start_date: "2026-04-01",
    end_date: "2026-10-30",
    created_by: "admin",
    created_at: "",
    updated_at: "",
    expenses: 1800000,
    progress: 68,
  },
  {
    id: "p2",
    project_code: "PRJ-2026-002",
    name: "FDAS & Suppression System",
    client_name: "SM Prime Holdings",
    site_location: "Pasig City",
    service_type: "FDAS",
    description: "Fire detection and alarm system with clean agent suppression.",
    contract_value: 4500000,
    budget: 3600000,
    status: "active",
    start_date: "2026-02-15",
    end_date: "2026-12-15",
    created_by: "admin",
    created_at: "",
    updated_at: "",
    expenses: 2150000,
    progress: 45,
  },
  {
    id: "p3",
    project_code: "PRJ-2025-014",
    name: "Preventive Maintenance",
    client_name: "Robinsons Land",
    site_location: "Quezon City",
    service_type: "Preventive Maintenance",
    description: "Quarterly PM contract for fire protection systems.",
    contract_value: 850000,
    budget: 700000,
    status: "completed",
    start_date: "2025-06-01",
    end_date: "2026-05-31",
    created_by: "admin",
    created_at: "",
    updated_at: "",
    expenses: 690000,
    progress: 100,
  },
  {
    id: "p4",
    project_code: "PRJ-2026-003",
    name: "Fire Alarm System Upgrade",
    client_name: "Megaworld Corp.",
    site_location: "Taguig City",
    service_type: "System Upgrade",
    description: "Upgrade of legacy conventional panel to addressable system.",
    contract_value: 1650000,
    budget: 1300000,
    status: "on_hold",
    start_date: "2026-05-10",
    end_date: null,
    created_by: "admin",
    created_at: "",
    updated_at: "",
    expenses: 420000,
    progress: 22,
  },
];

export const demoExpenses: Expense[] = [
  {
    id: "e1",
    project_id: "p1",
    category_id: "1",
    description: "Sprinkler heads and piping (batch 3)",
    amount: 185000,
    expense_date: "2026-08-28",
    vendor_name: "Metro Fire Supply Inc.",
    payment_method: "bank_transfer",
    status: "approved",
    submitted_by: "u2",
    receipt_path: null,
    created_at: "",
    updated_at: "",
    project_name: "Sprinkler System Installation",
    category_name: "Materials",
    submitted_by_name: "Mark Reyes",
  },
  {
    id: "e2",
    project_id: "p2",
    category_id: "2",
    description: "Installation crew — week 34",
    amount: 96500,
    expense_date: "2026-08-27",
    vendor_name: null,
    payment_method: "cash",
    status: "pending",
    submitted_by: "u3",
    receipt_path: null,
    created_at: "",
    updated_at: "",
    project_name: "FDAS & Suppression System",
    category_name: "Labor",
    submitted_by_name: "Liza Domingo",
  },
  {
    id: "e3",
    project_id: "p4",
    category_id: "3",
    description: "Rental — scissor lift (5 days)",
    amount: 42000,
    expense_date: "2026-08-25",
    vendor_name: "BuildRent Equipment",
    payment_method: "card",
    status: "approved",
    submitted_by: "u2",
    receipt_path: null,
    created_at: "",
    updated_at: "",
    project_name: "Fire Alarm System Upgrade",
    category_name: "Equipment",
    submitted_by_name: "Mark Reyes",
  },
  {
    id: "e4",
    project_id: "p1",
    category_id: "5",
    description: "Fuel — site vehicles",
    amount: 8750,
    expense_date: "2026-08-24",
    vendor_name: "Petron",
    payment_method: "cash",
    status: "rejected",
    submitted_by: "u3",
    receipt_path: null,
    created_at: "",
    updated_at: "",
    project_name: "Sprinkler System Installation",
    category_name: "Fuel",
    submitted_by_name: "Liza Domingo",
  },
  {
    id: "e5",
    project_id: "p2",
    category_id: "1",
    description: "Suppression cylinders (12 units)",
    amount: 310000,
    expense_date: "2026-08-20",
    vendor_name: "SafeGuard Fire Systems",
    payment_method: "bank_transfer",
    status: "approved",
    submitted_by: "u2",
    receipt_path: null,
    created_at: "",
    updated_at: "",
    project_name: "FDAS & Suppression System",
    category_name: "Materials",
    submitted_by_name: "Mark Reyes",
  },
];

export const demoDocuments: AppDocument[] = [
  {
    id: "d1",
    project_id: "p1",
    file_name: "Service_Contract_Ayala.pdf",
    file_path: "",
    file_type: "pdf",
    file_size: 482000,
    uploaded_by: "admin",
    created_at: "2026-04-02",
    project_name: "Sprinkler System Installation",
    category: "Contracts",
    uploaded_by_name: "Admin",
  },
  {
    id: "d2",
    project_id: "p2",
    file_name: "FDAS_Quotation_Rev2.xlsx",
    file_path: "",
    file_type: "xlsx",
    file_size: 128000,
    uploaded_by: "admin",
    created_at: "2026-02-10",
    project_name: "FDAS & Suppression System",
    category: "Quotations",
    uploaded_by_name: "Admin",
  },
  {
    id: "d3",
    project_id: "p3",
    file_name: "PM_Service_Report_Q2.pdf",
    file_path: "",
    file_type: "pdf",
    file_size: 265000,
    uploaded_by: "u2",
    created_at: "2026-06-18",
    project_name: "Preventive Maintenance",
    category: "Service Reports",
    uploaded_by_name: "Mark Reyes",
  },
];

export const expenseByCategoryDemo = [
  { name: "Materials", value: 495000, color: "#1f5fd6" },
  { name: "Labor", value: 96500, color: "#16a34a" },
  { name: "Equipment", value: 42000, color: "#7c3aed" },
  { name: "Transportation", value: 31000, color: "#ea9a1a" },
  { name: "Fuel", value: 8750, color: "#dc2626" },
  { name: "Tools", value: 15500, color: "#0b1b33" },
];

export const expensesOverTimeDemo = [
  { month: "Mar", amount: 320000 },
  { month: "Apr", amount: 410000 },
  { month: "May", amount: 385000 },
  { month: "Jun", amount: 512000 },
  { month: "Jul", amount: 468000 },
  { month: "Aug", amount: 589000 },
];
